"Font stuff
let g:Guifont="remixicon:h10"
let g:Guifont="Source\ Code\ Pro:h10"

" General
set encoding=UTF-8
syntax on                           " show syntax highlighting
set relativenumber                  " Show line numbers
set number                          " Set line numbers
set linebreak	                    " Break lines at word (requires Wrap lines)
set showbreak=+++	                " Wrap-broken line prefix
set textwidth=0	                    " Line wrap (number of cols)
set showmatch	                    " Highlight matching brace
" set spell	                        " Enable spell-checking
set visualbell	                    " Use visual bell (no beeping)

set smartcase	                    " Enable smart-case search
set gdefault	                    " Always substitute all matches in a line
set ignorecase	                    " Always case-insensitive
set incsearch	                    " Searches for strings incrementally
set nohlsearch                      " No longer highlight searches

set autoindent	                    " Auto-indent new lines
set cindent	                        " Use 'C' style program indenting
set expandtab	                    " Use spaces instead of tabs
set shiftwidth=4	                " Number of auto-indent spaces
set smartindent	                    " Enable smart-indent
set smarttab	                    " Enable smart-tabs
set tabstop=4	                    " Number of spaces per Tab
set softtabstop=4	                " Number of spaces per Tab

" Advanced
set confirm	                        " Prompt confirmation dialogs
set ruler	                        " Show row and column ruler information
set noshowmode
set noruler
set noshowcmd
set cmdheight=1
set nowrap
set hidden
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set scrolloff=8
set signcolumn=yes

set undolevels=1000	                " Number of undo levels
set backspace=indent,eol,start	    " Backspace behaviour

set nocompatible              " be iMproved, required
filetype off                  " required

call plug#begin('~/.vim/plugged')

Plug 'dracula/vim', { 'name': 'dracula' }

Plug 'nvim-lua/popup.nvim'
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-telescope/telescope.nvim'
Plug 'nvim-telescope/telescope-fzy-native.nvim'

Plug 'ap/vim-css-color'
Plug 'jremmen/vim-ripgrep'
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'
Plug 'leafgarland/typescript-vim'
Plug 'vim-utils/vim-man'
Plug 'lyuts/vim-rtags'
Plug 'mbbill/undotree'
Plug 'hoob3rt/lualine.nvim'
"Plug 'itchyny/lightline.vim'
Plug 'ryanoasis/vim-devicons'
Plug 'wakatime/vim-wakatime'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'valloric/youcompleteme'
Plug 'mhinz/vim-startify'

"Plug 'vim-airline/vim-airline'
"Plug 'vim-airline/vim-airline-themes'

" All of your Plugins must be added before the following line
call plug#end()             " required

filetype plugin indent on   " required
colorscheme dracula
set background=dark

if executable('rg')
    let g:rg_derive_root = 'true'
endif

let g:netrw_browse_split = 2
let g:netrw_banner = 0

source $VIMRUNTIME/mswin.vim
behave mswin

" set the leader key
let mapleader = " "

fun! TrimWhitespace()
    let l:save = winsaveview()
    keeppatterns %s/\s\+$//e
    call winrestview(l:save)
endfun

augroup TheRepoClub
    autocmd!
    autocmd BufWritePre * :call TrimWhitespace()
augroup END
